workflows:
  ios-app:
    name: iOS Build
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: EAS Build for iOS
        script: |
          npx expo prebuild --platform ios
          npx eas build -p ios --non-interactive
    artifacts:
      - build/ios/ipa/*.ipa
