workflows:
  ios-release:
    name: iOS Release
    environment:
      vars:
        BUNDLE_ID: com.firegatebioscience.watchman
    scripts:
      - name: Set bundle identifier
        script: |
          echo "Overriding bundle ID in Xcode project"
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" ios/Watchman.xcodeproj/project.pbxproj
    artifacts:
      - build/ios/**/*.ipa
