workflows:
  watchman-ios:
    name: Watchman iOS Build
    environment:
      groups:
        - FireGate2  # <- Use the group where your CERTIFICATE, PROVISIONING_PROFILE, and CERTIFICATE_PASSWORD are set
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.firegatebioscience.watchman
        provisioning_profile_name: WatchmanAppStore
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - npm install -g expo-cli eas-cli
      - npm install
      - eas build:configure --platform ios
      - npx expo prebuild --platform ios
      - npx eas build -p ios --non-interactive
    artifacts:
      - build/ios/ipa/*.ipa
