workflows:
  watchman-ios:
    name: Watchman iOS Build
    environment:
      groups:
        - FireGate2
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    signing:
      certificates:
        - certificate: $CERTIFICATE
          password: $CERTIFICATE_PASSWORD
      provisioning_profiles:
        - provisioning_profile: $PROVISIONING_PROFILE
    scripts:
      - npm install -g expo-cli eas-cli
      - npm install
      - eas build:configure --platform ios
      - npx expo prebuild --platform ios
      - npx eas build -p ios --non-interactive
    artifacts:
      - build/ios/ipa/*.ipa
