workflows:
  ios-release:
    name: iOS Release
    environment:
      xcode: latest
      vars:
        XCODE_WORKSPACE: ios/Watchman.xcworkspace
        XCODE_SCHEME: Watchman
    scripts:
      - name: Install JS dependencies
        script: |
          echo "Installing JS dependencies..."
          # prefer lockfile if present
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable || true
            yarn install --frozen-lockfile || yarn install
          else
            npm install
          fi
          node -v
          npm -v || yarn -v || true

      - name: Install CocoaPods and generate workspace
        script: |
          echo "Installing CocoaPods..."
          cd ios
          pod install --repo-update
          ls -la
          if [ ! -d "Watchman.xcworkspace" ]; then
            echo "❌ Watchman.xcworkspace not found after pod install"
            exit 1
          fi
          cd ..

      - name: Build IPA using xcodebuild
        script: |
          echo "Archiving app..."
          xcodebuild clean archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/Watchman.xcarchive \
            -configuration Release \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=9295GJRZLK \
            -allowProvisioningUpdates

          echo "Exporting IPA..."
          xcodebuild -exportArchive \
            -archivePath build/Watchman.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
