workflows:
  react-native-app:
    name: Watchman App Build
    instance_type: mac_mini_m1
    environment:
      node: 18
    scripts:
      - npm install -g expo-cli
      - npm install
      - npx expo prebuild --platform android
      - npx expo build:android --non-interactive
    artifacts:
      - dist/**/*.apk
      - dist/**/*.aab
