workflows:
  ios-release:
    name: iOS Release
    environment:
      xcode: latest
      ruby: 3.1.2
      vars:
        XCODE_PROJECT: ios/Watchman.xcodeproj
        XCODE_SCHEME: Watchman
    scripts:
      - name: Set bundle identifier
        script: |
          echo "Setting bundle identifier..."
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = com.firegatebioscience.watchman;/g" ios/Watchman.xcodeproj/project.pbxproj

      - name: Install CocoaPods
        script: |
          echo "Installing CocoaPods..."
          cd ios
          pod install || true
          cd ..

      - name: Build IPA using xcodebuild
        script: |
          echo "Archiving app..."
          xcodebuild clean archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/Watchman.xcarchive \
            -configuration Release \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=YOUR_TEAM_ID_HERE \
            -allowProvisioningUpdates

          echo "Exporting IPA..."
          xcodebuild -exportArchive \
            -archivePath build/Watchman.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
