workflows:
  react-native-app:
    name: Watchman App Build
    instance_type: mac_mini_m1
    environment:
      node: 18
      vars:
        EXPO_TOKEN: "9qqM3cGBBlwy9x5jXnBiOikVe3Rc-hjTFvv70kwf"
    scripts:
      - npm install -g expo-cli eas-cli
      - npm install
      - npx expo prebuild --platform android
      - npx eas build -p android --non-interactive
    artifacts:
      - build/**/*
