workflows:
  ios-release:
    name: iOS Release
    environment:
      xcode: latest
      vars:
        XCODE_WORKSPACE: ios/Watchman.xcworkspace
        XCODE_SCHEME: Watchman
    scripts:
      - name: Clean & Install Pods
        script: |
          echo "Installing CocoaPods..."
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Set bundle identifier
        script: |
          echo "Setting bundle identifier..."
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = com.firegatebioscience.watchman;/g" ios/Watchman.xcodeproj/project.pbxproj

      - name: Build IPA using xcodebuild
        script: |
          echo "Archiving app..."
          xcodebuild clean archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/Watchman.xcarchive \
            -configuration Release \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=YOUR_TEAM_ID_HERE \
            -allowProvisioningUpdates

          echo "Exporting IPA..."
          xcodebuild -exportArchive \
            -archivePath build/Watchman.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
