workflows:
  ios-release:
    name: iOS Release
    environment:
      vars:
        BUNDLE_ID: com.firegatebioscience.watchman
    scripts:
      - name: Set bundle ID
        script: |
          echo "Setting bundle identifier to $BUNDLE_ID"
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" ios/*/*.xcodeproj/project.pbxproj
    artifacts:
      - build/ios/ipa/*.ipa
