workflows:
  watchman-ios:
    name: Watchman iOS Build
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.firegatebioscience.watchman
      vars:
        PROVISIONING_PROFILE: $PROVISIONING_PROFILE
        P12_BASE64: $P12_BASE64
        CERT_PASSWORD: $CERT_PASSWORD
      groups:
        - FireGate
      node: 18
    scripts:
      - npm install -g expo-cli eas-cli
      - npm install
      - eas build:configure --platform ios
      - npx expo prebuild --platform ios
      - npx eas build -p ios --non-interactive
    artifacts:
      - build/ios/ipa/*.ipa
