workflows:
  watchman-app:
    name: Watchman iOS Build
    environment:
      node: 18
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - npm install -g expo-cli eas-cli
      - npm install
      - npx expo prebuild --platform ios
      - npx eas build -p ios --non-interactive
