workflows:
  ios-release:
    name: iOS Release
    environment:
      xcode: latest
      vars:
        XCODE_WORKSPACE: ios/WatchmanWorkspace
        XCODE_SCHEME: Watchman
    scripts:
      - name: Build IPA using xcodebuild
        script: |
          echo "Archiving app..."
          xcodebuild clean archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/Watchman.xcarchive \
            -configuration Release \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=YOUR_TEAM_ID_HERE \
            -allowProvisioningUpdates

          echo "Exporting IPA..."
          xcodebuild -exportArchive \
            -archivePath build/Watchman.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
