workflows:
  react-native-app:
    name: Watchman App Build
    instance_type: mac_mini_m1
    environment:
      node: 18
    scripts:
      - npm install
      - npx expo install
      - npx expo prebuild --platform android
      - npx expo run:android
    artifacts:
      - android/app/build/outputs/**/*.apk
